apiVersion: apps/v1
kind: Deployment

metadata: 
 name: cka-web



spec:
  replicas: 3


  selector:
   matchLabels: 
     app: cka-web


  template:
   metadata:
     labels:
      app: cka-web


   spec: 
    containers:
     - name: nginx
       image: nginx


