apiVersion: batch/v1
kind: CronJob
metadata:
  name: rachit
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: rachit
              image: nginx
              command: ["/bin/sh", "-c", "echo Technical-Guftgu; sleep 5"]
          restartPolicy: Never
