apiVersion: v1
kind: Pod
metadata:
  name: constraints-mem-demo2
spec:
  containers:
   - name: constraints-mem-demo-ctr
     image: nginx
     resources:
       limits:
         memory: "1300Mi"
       requests:
         memory: "600Mi"
