apiVersion: v1
kind: Pod

metadata:
  name: environments

spec:
  containers:
    - name: c00
      image: ubuntu
      command: ["/bin/bash"]
      args: ["-c", "while true; do sleep 10; done"]
      env:
        - name: MYNAME
          value: RACHIT
