apiVersion: v1
kind: Pod
metadata:
  name: labelpod
  labels: 
    env: development
    class: pods


spec:
  containers: 
    - name: coo8
      image: ubuntu
      command: ["/bin/bash","-c","while true; do echo hello-rachit; sleep 5 ; done"]


