kind: Pod
apiVersion: v1
metadata: 
  name: nodelabels
  labels:
    env: dev


spec: 
  containers:
    - name: ros
      image: ubuntu
      command: ["/bin/bash" , "-c" , "while true; do echo hello-rachit; sleep ; done"]
  nodeSelector:
    hardware: t2-medium
 
